local DiscordLib = loadstring(game:HttpGet"https://raw.githubusercontent.com/dawid-scripts/UI-Libs/main/discord%20lib.txt")()

local win = DiscordLib:Window("discord library")

local serv = win:Server("Preview", "")

local tgls = serv:Channel("Toggles")



tgls:Toggle("PlantSeed Potion",false, function(bool)
_G.K = bool
while _G.K do 
wait(0.01)
local args = {
    [1] = "FlowerGarden",
    [2] = "PlantSeed",
    [3] = 1,
    [4] = "Potion"
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))
wait(0.01)
local args = {
    [1] = "FlowerGarden",
    [2] = "PlantSeed",
    [3] = 2,
    [4] = "Potion"
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))
wait(0.01)
local args = {
    [1] = "FlowerGarden",
    [2] = "PlantSeed",
    [3] = 3,
    [4] = "Potion"
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))
wait(0.01)
local args = {
    [1] = "FlowerGarden",
    [2] = "PlantSeed",
    [3] = 4,
    [4] = "Potion"
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))
wait(0.01)
local args = {
    [1] = "FlowerGarden",
    [2] = "PlantSeed",
    [3] = 5,
    [4] = "Potion"
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))
wait(0.01)
local args = {
    [1] = "FlowerGarden",
    [2] = "PlantSeed",
    [3] = 6,
    [4] = "Potion"
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))
wait(0.01)
local args = {
    [1] = "FlowerGarden",
    [2] = "PlantSeed",
    [3] = 7,
    [4] = "Potion"
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))
wait(0.01)
local args = {
    [1] = "FlowerGarden",
    [2] = "PlantSeed",
    [3] = 8,
    [4] = "Potion"
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))
wait(0.01)
local args = {
    [1] = "FlowerGarden",
    [2] = "PlantSeed",
    [3] = 9,
    [4] = "Potion"
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))
wait(0.01)
local args = {
    [1] = "FlowerGarden",
    [2] = "PlantSeed",
    [3] = 10,
    [4] = "Potion"
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))
wait(0.01)
end
end)

tgls:Toggle("WaterSeed",false, function(bool)
_G.H = bool
while _G.H do 
wait(0.01)
local args = {
    [1] = "FlowerGarden",
    [2] = "WaterSeed",
    [3] = 1
}
 game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "WaterSeed",
    [3] = 2
}
     game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))
     
wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "WaterSeed",
    [3] = 3
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "WaterSeed",
    [3] = 4
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "WaterSeed",
    [3] = 5
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "WaterSeed",
    [3] = 6
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "WaterSeed",
    [3] = 7
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "WaterSeed",
    [3] = 8
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "WaterSeed",
    [3] = 9
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "WaterSeed",
    [3] = 10
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_InvokeCustomFromClient"):InvokeServer(unpack(args))
end
end)


tgls:Toggle("ClaimPlant",false, function(bool)
_G.G = bool
while _G.G do 
wait(0.01)
local args = {
    [1] = "FlowerGarden",
    [2] = "ClaimPlant",
    [3] = 1
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_FireCustomFromClient"):FireServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "ClaimPlant",
    [3] = 2
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_FireCustomFromClient"):FireServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "ClaimPlant",
    [3] = 3
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_FireCustomFromClient"):FireServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "ClaimPlant",
    [3] = 4
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_FireCustomFromClient"):FireServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "ClaimPlant",
    [3] = 5
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_FireCustomFromClient"):FireServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "ClaimPlant",
    [3] = 6
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_FireCustomFromClient"):FireServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "ClaimPlant",
    [3] = 7
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_FireCustomFromClient"):FireServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "ClaimPlant",
    [3] = 8
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_FireCustomFromClient"):FireServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "ClaimPlant",
    [3] = 9
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_FireCustomFromClient"):FireServer(unpack(args))

wait(0.01)

local args = {
    [1] = "FlowerGarden",
    [2] = "ClaimPlant",
    [3] = 10
}

game:GetService("ReplicatedStorage"):WaitForChild("Network"):WaitForChild("Instancing_FireCustomFromClient"):FireServer(unpack(args))
end
end)
